apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app.kubernetes.io/component: order
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: order
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
    - name: metrics
      port: 9104
      targetPort: metrics
