// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: marketdata/v1/marketdata.proto

package marketdatav1

import (
	v1 "github.com/Grizzly1127/trading_matchengine/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReferencePriceKind 市价买单冻结等场景的参考价类型。
type ReferencePriceKind int32

const (
	ReferencePriceKind_REFERENCE_PRICE_KIND_UNSPECIFIED ReferencePriceKind = 0
	ReferencePriceKind_REFERENCE_PRICE_KIND_BEST_ASK    ReferencePriceKind = 1
	ReferencePriceKind_REFERENCE_PRICE_KIND_MARK        ReferencePriceKind = 2
	ReferencePriceKind_REFERENCE_PRICE_KIND_LAST        ReferencePriceKind = 3
)

// Enum value maps for ReferencePriceKind.
var (
	ReferencePriceKind_name = map[int32]string{
		0: "REFERENCE_PRICE_KIND_UNSPECIFIED",
		1: "REFERENCE_PRICE_KIND_BEST_ASK",
		2: "REFERENCE_PRICE_KIND_MARK",
		3: "REFERENCE_PRICE_KIND_LAST",
	}
	ReferencePriceKind_value = map[string]int32{
		"REFERENCE_PRICE_KIND_UNSPECIFIED": 0,
		"REFERENCE_PRICE_KIND_BEST_ASK":    1,
		"REFERENCE_PRICE_KIND_MARK":        2,
		"REFERENCE_PRICE_KIND_LAST":        3,
	}
)

func (x ReferencePriceKind) Enum() *ReferencePriceKind {
	p := new(ReferencePriceKind)
	*p = x
	return p
}

func (x ReferencePriceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferencePriceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_marketdata_v1_marketdata_proto_enumTypes[0].Descriptor()
}

func (ReferencePriceKind) Type() protoreflect.EnumType {
	return &file_marketdata_v1_marketdata_proto_enumTypes[0]
}

func (x ReferencePriceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferencePriceKind.Descriptor instead.
func (ReferencePriceKind) EnumDescriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{0}
}

// PriceLevel 盘口单档（价格 + 数量，十进制字符串）。
type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *v1.Decimal            `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      *v1.Decimal            `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *PriceLevel) GetPrice() *v1.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *PriceLevel) GetQuantity() *v1.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

type GetOrderBookRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Symbol string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 每边档位数，默认 20，最大 100。
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderBookRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastUpdateId  uint64                 `protobuf:"varint,2,opt,name=last_update_id,json=lastUpdateId,proto3" json:"last_update_id,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookResponse) Reset() {
	*x = GetOrderBookResponse{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookResponse) ProtoMessage() {}

func (x *GetOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookResponse.ProtoReflect.Descriptor instead.
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderBookResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderBookResponse) GetLastUpdateId() uint64 {
	if x != nil {
		return x.LastUpdateId
	}
	return 0
}

func (x *GetOrderBookResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetOrderBookResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetOrderBookResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Ticker 单交易对 24h 行情。
type Ticker struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Symbol             string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastPrice          *v1.Decimal            `protobuf:"bytes,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	OpenPrice          *v1.Decimal            `protobuf:"bytes,3,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	HighPrice          *v1.Decimal            `protobuf:"bytes,4,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	LowPrice           *v1.Decimal            `protobuf:"bytes,5,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	Volume             *v1.Decimal            `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	QuoteVolume        *v1.Decimal            `protobuf:"bytes,7,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`
	PriceChangePercent *v1.Decimal            `protobuf:"bytes,8,opt,name=price_change_percent,json=priceChangePercent,proto3" json:"price_change_percent,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *Ticker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Ticker) GetLastPrice() *v1.Decimal {
	if x != nil {
		return x.LastPrice
	}
	return nil
}

func (x *Ticker) GetOpenPrice() *v1.Decimal {
	if x != nil {
		return x.OpenPrice
	}
	return nil
}

func (x *Ticker) GetHighPrice() *v1.Decimal {
	if x != nil {
		return x.HighPrice
	}
	return nil
}

func (x *Ticker) GetLowPrice() *v1.Decimal {
	if x != nil {
		return x.LowPrice
	}
	return nil
}

func (x *Ticker) GetVolume() *v1.Decimal {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *Ticker) GetQuoteVolume() *v1.Decimal {
	if x != nil {
		return x.QuoteVolume
	}
	return nil
}

func (x *Ticker) GetPriceChangePercent() *v1.Decimal {
	if x != nil {
		return x.PriceChangePercent
	}
	return nil
}

func (x *Ticker) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetTickerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// symbol 与 symbols 二选一；symbols 最多 100 个。
	Symbol        string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Symbols       []string `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickerRequest) Reset() {
	*x = GetTickerRequest{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerRequest) ProtoMessage() {}

func (x *GetTickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerRequest.ProtoReflect.Descriptor instead.
func (*GetTickerRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{4}
}

func (x *GetTickerRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTickerRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type GetTickerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 单 symbol 查询时填充 ticker；批量查询时填充 items。
	Ticker        *Ticker   `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Items         []*Ticker `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickerResponse) Reset() {
	*x = GetTickerResponse{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerResponse) ProtoMessage() {}

func (x *GetTickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerResponse.ProtoReflect.Descriptor instead.
func (*GetTickerResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{5}
}

func (x *GetTickerResponse) GetTicker() *Ticker {
	if x != nil {
		return x.Ticker
	}
	return nil
}

func (x *GetTickerResponse) GetItems() []*Ticker {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetReferencePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Kind          ReferencePriceKind     `protobuf:"varint,2,opt,name=kind,proto3,enum=marketdata.v1.ReferencePriceKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferencePriceRequest) Reset() {
	*x = GetReferencePriceRequest{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferencePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferencePriceRequest) ProtoMessage() {}

func (x *GetReferencePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferencePriceRequest.ProtoReflect.Descriptor instead.
func (*GetReferencePriceRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{6}
}

func (x *GetReferencePriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetReferencePriceRequest) GetKind() ReferencePriceKind {
	if x != nil {
		return x.Kind
	}
	return ReferencePriceKind_REFERENCE_PRICE_KIND_UNSPECIFIED
}

type GetReferencePriceResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Price       *v1.Decimal            `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	UpdatedAtMs int64                  `protobuf:"varint,2,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	// 降级后实际采用的参考价类型（如请求 BEST_ASK 无盘时用 LAST）。
	ResolvedKind  ReferencePriceKind `protobuf:"varint,3,opt,name=resolved_kind,json=resolvedKind,proto3,enum=marketdata.v1.ReferencePriceKind" json:"resolved_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferencePriceResponse) Reset() {
	*x = GetReferencePriceResponse{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferencePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferencePriceResponse) ProtoMessage() {}

func (x *GetReferencePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferencePriceResponse.ProtoReflect.Descriptor instead.
func (*GetReferencePriceResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{7}
}

func (x *GetReferencePriceResponse) GetPrice() *v1.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *GetReferencePriceResponse) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *GetReferencePriceResponse) GetResolvedKind() ReferencePriceKind {
	if x != nil {
		return x.ResolvedKind
	}
	return ReferencePriceKind_REFERENCE_PRICE_KIND_UNSPECIFIED
}

type GetTickerAllSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 过滤计价币，如 USDT；空表示全部 TRADING 交易对。
	QuoteAsset string `protobuf:"bytes,1,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	// 若与服务端当前 snapshot_id 一致，响应 not_modified=true。
	SnapshotId    string `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickerAllSnapshotRequest) Reset() {
	*x = GetTickerAllSnapshotRequest{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickerAllSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerAllSnapshotRequest) ProtoMessage() {}

func (x *GetTickerAllSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerAllSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetTickerAllSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{8}
}

func (x *GetTickerAllSnapshotRequest) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *GetTickerAllSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

// TickerAllItem 全市场 Ticker 条目（与 REST/WS 短字段可对齐扩展）。
type TickerAllItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Symbol             string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastPrice          *v1.Decimal            `protobuf:"bytes,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Volume             *v1.Decimal            `protobuf:"bytes,3,opt,name=volume,proto3" json:"volume,omitempty"`
	QuoteVolume        *v1.Decimal            `protobuf:"bytes,4,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`
	PriceChangePercent *v1.Decimal            `protobuf:"bytes,5,opt,name=price_change_percent,json=priceChangePercent,proto3" json:"price_change_percent,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TickerAllItem) Reset() {
	*x = TickerAllItem{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerAllItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerAllItem) ProtoMessage() {}

func (x *TickerAllItem) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerAllItem.ProtoReflect.Descriptor instead.
func (*TickerAllItem) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{9}
}

func (x *TickerAllItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TickerAllItem) GetLastPrice() *v1.Decimal {
	if x != nil {
		return x.LastPrice
	}
	return nil
}

func (x *TickerAllItem) GetVolume() *v1.Decimal {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *TickerAllItem) GetQuoteVolume() *v1.Decimal {
	if x != nil {
		return x.QuoteVolume
	}
	return nil
}

func (x *TickerAllItem) GetPriceChangePercent() *v1.Decimal {
	if x != nil {
		return x.PriceChangePercent
	}
	return nil
}

func (x *TickerAllItem) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetTickerAllSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	SnapshotTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=snapshot_time,json=snapshotTime,proto3" json:"snapshot_time,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Items         []*TickerAllItem       `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	NotModified   bool                   `protobuf:"varint,5,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickerAllSnapshotResponse) Reset() {
	*x = GetTickerAllSnapshotResponse{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickerAllSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerAllSnapshotResponse) ProtoMessage() {}

func (x *GetTickerAllSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerAllSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetTickerAllSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{10}
}

func (x *GetTickerAllSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *GetTickerAllSnapshotResponse) GetSnapshotTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotTime
	}
	return nil
}

func (x *GetTickerAllSnapshotResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetTickerAllSnapshotResponse) GetItems() []*TickerAllItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetTickerAllSnapshotResponse) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

var File_marketdata_v1_marketdata_proto protoreflect.FileDescriptor

const file_marketdata_v1_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x1emarketdata/v1/marketdata.proto\x12\rmarketdata.v1\x1a\x15common/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\n" +
	"PriceLevel\x12(\n" +
	"\x05price\x18\x01 \x01(\v2\x12.common.v1.DecimalR\x05price\x12.\n" +
	"\bquantity\x18\x02 \x01(\v2\x12.common.v1.DecimalR\bquantity\"C\n" +
	"\x13GetOrderBookRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xec\x01\n" +
	"\x14GetOrderBookResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12$\n" +
	"\x0elast_update_id\x18\x02 \x01(\x04R\flastUpdateId\x12-\n" +
	"\x04bids\x18\x03 \x03(\v2\x19.marketdata.v1.PriceLevelR\x04bids\x12-\n" +
	"\x04asks\x18\x04 \x03(\v2\x19.marketdata.v1.PriceLevelR\x04asks\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xcd\x03\n" +
	"\x06Ticker\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x121\n" +
	"\n" +
	"last_price\x18\x02 \x01(\v2\x12.common.v1.DecimalR\tlastPrice\x121\n" +
	"\n" +
	"open_price\x18\x03 \x01(\v2\x12.common.v1.DecimalR\topenPrice\x121\n" +
	"\n" +
	"high_price\x18\x04 \x01(\v2\x12.common.v1.DecimalR\thighPrice\x12/\n" +
	"\tlow_price\x18\x05 \x01(\v2\x12.common.v1.DecimalR\blowPrice\x12*\n" +
	"\x06volume\x18\x06 \x01(\v2\x12.common.v1.DecimalR\x06volume\x125\n" +
	"\fquote_volume\x18\a \x01(\v2\x12.common.v1.DecimalR\vquoteVolume\x12D\n" +
	"\x14price_change_percent\x18\b \x01(\v2\x12.common.v1.DecimalR\x12priceChangePercent\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"D\n" +
	"\x10GetTickerRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\"o\n" +
	"\x11GetTickerResponse\x12-\n" +
	"\x06ticker\x18\x01 \x01(\v2\x15.marketdata.v1.TickerR\x06ticker\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.marketdata.v1.TickerR\x05items\"i\n" +
	"\x18GetReferencePriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x125\n" +
	"\x04kind\x18\x02 \x01(\x0e2!.marketdata.v1.ReferencePriceKindR\x04kind\"\xb1\x01\n" +
	"\x19GetReferencePriceResponse\x12(\n" +
	"\x05price\x18\x01 \x01(\v2\x12.common.v1.DecimalR\x05price\x12\"\n" +
	"\rupdated_at_ms\x18\x02 \x01(\x03R\vupdatedAtMs\x12F\n" +
	"\rresolved_kind\x18\x03 \x01(\x0e2!.marketdata.v1.ReferencePriceKindR\fresolvedKind\"_\n" +
	"\x1bGetTickerAllSnapshotRequest\x12\x1f\n" +
	"\vquote_asset\x18\x01 \x01(\tR\n" +
	"quoteAsset\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"\xbd\x02\n" +
	"\rTickerAllItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x121\n" +
	"\n" +
	"last_price\x18\x02 \x01(\v2\x12.common.v1.DecimalR\tlastPrice\x12*\n" +
	"\x06volume\x18\x03 \x01(\v2\x12.common.v1.DecimalR\x06volume\x125\n" +
	"\fquote_volume\x18\x04 \x01(\v2\x12.common.v1.DecimalR\vquoteVolume\x12D\n" +
	"\x14price_change_percent\x18\x05 \x01(\v2\x12.common.v1.DecimalR\x12priceChangePercent\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xed\x01\n" +
	"\x1cGetTickerAllSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12?\n" +
	"\rsnapshot_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fsnapshotTime\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x122\n" +
	"\x05items\x18\x04 \x03(\v2\x1c.marketdata.v1.TickerAllItemR\x05items\x12!\n" +
	"\fnot_modified\x18\x05 \x01(\bR\vnotModified*\x9b\x01\n" +
	"\x12ReferencePriceKind\x12$\n" +
	" REFERENCE_PRICE_KIND_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dREFERENCE_PRICE_KIND_BEST_ASK\x10\x01\x12\x1d\n" +
	"\x19REFERENCE_PRICE_KIND_MARK\x10\x02\x12\x1d\n" +
	"\x19REFERENCE_PRICE_KIND_LAST\x10\x032\x95\x03\n" +
	"\x11MarketDataService\x12W\n" +
	"\fGetOrderBook\x12\".marketdata.v1.GetOrderBookRequest\x1a#.marketdata.v1.GetOrderBookResponse\x12N\n" +
	"\tGetTicker\x12\x1f.marketdata.v1.GetTickerRequest\x1a .marketdata.v1.GetTickerResponse\x12f\n" +
	"\x11GetReferencePrice\x12'.marketdata.v1.GetReferencePriceRequest\x1a(.marketdata.v1.GetReferencePriceResponse\x12o\n" +
	"\x14GetTickerAllSnapshot\x12*.marketdata.v1.GetTickerAllSnapshotRequest\x1a+.marketdata.v1.GetTickerAllSnapshotResponseBNZLgithub.com/Grizzly1127/trading_matchengine/pkg/pb/marketdata/v1;marketdatav1b\x06proto3"

var (
	file_marketdata_v1_marketdata_proto_rawDescOnce sync.Once
	file_marketdata_v1_marketdata_proto_rawDescData []byte
)

func file_marketdata_v1_marketdata_proto_rawDescGZIP() []byte {
	file_marketdata_v1_marketdata_proto_rawDescOnce.Do(func() {
		file_marketdata_v1_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketdata_v1_marketdata_proto_rawDesc), len(file_marketdata_v1_marketdata_proto_rawDesc)))
	})
	return file_marketdata_v1_marketdata_proto_rawDescData
}

var file_marketdata_v1_marketdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_marketdata_v1_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_marketdata_v1_marketdata_proto_goTypes = []any{
	(ReferencePriceKind)(0),              // 0: marketdata.v1.ReferencePriceKind
	(*PriceLevel)(nil),                   // 1: marketdata.v1.PriceLevel
	(*GetOrderBookRequest)(nil),          // 2: marketdata.v1.GetOrderBookRequest
	(*GetOrderBookResponse)(nil),         // 3: marketdata.v1.GetOrderBookResponse
	(*Ticker)(nil),                       // 4: marketdata.v1.Ticker
	(*GetTickerRequest)(nil),             // 5: marketdata.v1.GetTickerRequest
	(*GetTickerResponse)(nil),            // 6: marketdata.v1.GetTickerResponse
	(*GetReferencePriceRequest)(nil),     // 7: marketdata.v1.GetReferencePriceRequest
	(*GetReferencePriceResponse)(nil),    // 8: marketdata.v1.GetReferencePriceResponse
	(*GetTickerAllSnapshotRequest)(nil),  // 9: marketdata.v1.GetTickerAllSnapshotRequest
	(*TickerAllItem)(nil),                // 10: marketdata.v1.TickerAllItem
	(*GetTickerAllSnapshotResponse)(nil), // 11: marketdata.v1.GetTickerAllSnapshotResponse
	(*v1.Decimal)(nil),                   // 12: common.v1.Decimal
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_marketdata_v1_marketdata_proto_depIdxs = []int32{
	12, // 0: marketdata.v1.PriceLevel.price:type_name -> common.v1.Decimal
	12, // 1: marketdata.v1.PriceLevel.quantity:type_name -> common.v1.Decimal
	1,  // 2: marketdata.v1.GetOrderBookResponse.bids:type_name -> marketdata.v1.PriceLevel
	1,  // 3: marketdata.v1.GetOrderBookResponse.asks:type_name -> marketdata.v1.PriceLevel
	13, // 4: marketdata.v1.GetOrderBookResponse.timestamp:type_name -> google.protobuf.Timestamp
	12, // 5: marketdata.v1.Ticker.last_price:type_name -> common.v1.Decimal
	12, // 6: marketdata.v1.Ticker.open_price:type_name -> common.v1.Decimal
	12, // 7: marketdata.v1.Ticker.high_price:type_name -> common.v1.Decimal
	12, // 8: marketdata.v1.Ticker.low_price:type_name -> common.v1.Decimal
	12, // 9: marketdata.v1.Ticker.volume:type_name -> common.v1.Decimal
	12, // 10: marketdata.v1.Ticker.quote_volume:type_name -> common.v1.Decimal
	12, // 11: marketdata.v1.Ticker.price_change_percent:type_name -> common.v1.Decimal
	13, // 12: marketdata.v1.Ticker.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 13: marketdata.v1.GetTickerResponse.ticker:type_name -> marketdata.v1.Ticker
	4,  // 14: marketdata.v1.GetTickerResponse.items:type_name -> marketdata.v1.Ticker
	0,  // 15: marketdata.v1.GetReferencePriceRequest.kind:type_name -> marketdata.v1.ReferencePriceKind
	12, // 16: marketdata.v1.GetReferencePriceResponse.price:type_name -> common.v1.Decimal
	0,  // 17: marketdata.v1.GetReferencePriceResponse.resolved_kind:type_name -> marketdata.v1.ReferencePriceKind
	12, // 18: marketdata.v1.TickerAllItem.last_price:type_name -> common.v1.Decimal
	12, // 19: marketdata.v1.TickerAllItem.volume:type_name -> common.v1.Decimal
	12, // 20: marketdata.v1.TickerAllItem.quote_volume:type_name -> common.v1.Decimal
	12, // 21: marketdata.v1.TickerAllItem.price_change_percent:type_name -> common.v1.Decimal
	13, // 22: marketdata.v1.TickerAllItem.timestamp:type_name -> google.protobuf.Timestamp
	13, // 23: marketdata.v1.GetTickerAllSnapshotResponse.snapshot_time:type_name -> google.protobuf.Timestamp
	10, // 24: marketdata.v1.GetTickerAllSnapshotResponse.items:type_name -> marketdata.v1.TickerAllItem
	2,  // 25: marketdata.v1.MarketDataService.GetOrderBook:input_type -> marketdata.v1.GetOrderBookRequest
	5,  // 26: marketdata.v1.MarketDataService.GetTicker:input_type -> marketdata.v1.GetTickerRequest
	7,  // 27: marketdata.v1.MarketDataService.GetReferencePrice:input_type -> marketdata.v1.GetReferencePriceRequest
	9,  // 28: marketdata.v1.MarketDataService.GetTickerAllSnapshot:input_type -> marketdata.v1.GetTickerAllSnapshotRequest
	3,  // 29: marketdata.v1.MarketDataService.GetOrderBook:output_type -> marketdata.v1.GetOrderBookResponse
	6,  // 30: marketdata.v1.MarketDataService.GetTicker:output_type -> marketdata.v1.GetTickerResponse
	8,  // 31: marketdata.v1.MarketDataService.GetReferencePrice:output_type -> marketdata.v1.GetReferencePriceResponse
	11, // 32: marketdata.v1.MarketDataService.GetTickerAllSnapshot:output_type -> marketdata.v1.GetTickerAllSnapshotResponse
	29, // [29:33] is the sub-list for method output_type
	25, // [25:29] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_marketdata_v1_marketdata_proto_init() }
func file_marketdata_v1_marketdata_proto_init() {
	if File_marketdata_v1_marketdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketdata_v1_marketdata_proto_rawDesc), len(file_marketdata_v1_marketdata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketdata_v1_marketdata_proto_goTypes,
		DependencyIndexes: file_marketdata_v1_marketdata_proto_depIdxs,
		EnumInfos:         file_marketdata_v1_marketdata_proto_enumTypes,
		MessageInfos:      file_marketdata_v1_marketdata_proto_msgTypes,
	}.Build()
	File_marketdata_v1_marketdata_proto = out.File
	file_marketdata_v1_marketdata_proto_goTypes = nil
	file_marketdata_v1_marketdata_proto_depIdxs = nil
}
