CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    client_order_id VARCHAR(64) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    side SMALLINT NOT NULL,
    order_type SMALLINT NOT NULL,
    price NUMERIC(36, 18),
    quantity NUMERIC(36, 18) NOT NULL,
    filled_quantity NUMERIC(36, 18) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS client_order_idempotency (
    user_id BIGINT NOT NULL,
    client_order_id VARCHAR(64) NOT NULL,
    order_id BIGINT NOT NULL REFERENCES orders (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, client_order_id)
);

CREATE INDEX IF NOT EXISTS idx_orders_user_status ON orders (user_id, status);
