// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: matching/v1/admin.proto

package matchingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderPresence 撮合侧订单存在性（Order Service 超时补偿对账，§4.5 / §5.6）。
type OrderPresence int32

const (
	OrderPresence_ORDER_PRESENCE_UNSPECIFIED OrderPresence = 0
	// 撮合引擎从未应用过该 order_id 的命令（可能 Kafka 未消费或分区不一致）。
	OrderPresence_ORDER_PRESENCE_UNKNOWN OrderPresence = 1
	// 订单仍在盘口挂单中。
	OrderPresence_ORDER_PRESENCE_IN_ORDERBOOK OrderPresence = 2
	// 已处理过但不在盘口（可能已成交或已撤，等待 match.events 回写）。
	OrderPresence_ORDER_PRESENCE_KNOWN_NOT_IN_ORDERBOOK OrderPresence = 3
)

// Enum value maps for OrderPresence.
var (
	OrderPresence_name = map[int32]string{
		0: "ORDER_PRESENCE_UNSPECIFIED",
		1: "ORDER_PRESENCE_UNKNOWN",
		2: "ORDER_PRESENCE_IN_ORDERBOOK",
		3: "ORDER_PRESENCE_KNOWN_NOT_IN_ORDERBOOK",
	}
	OrderPresence_value = map[string]int32{
		"ORDER_PRESENCE_UNSPECIFIED":            0,
		"ORDER_PRESENCE_UNKNOWN":                1,
		"ORDER_PRESENCE_IN_ORDERBOOK":           2,
		"ORDER_PRESENCE_KNOWN_NOT_IN_ORDERBOOK": 3,
	}
)

func (x OrderPresence) Enum() *OrderPresence {
	p := new(OrderPresence)
	*p = x
	return p
}

func (x OrderPresence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderPresence) Descriptor() protoreflect.EnumDescriptor {
	return file_matching_v1_admin_proto_enumTypes[0].Descriptor()
}

func (OrderPresence) Type() protoreflect.EnumType {
	return &file_matching_v1_admin_proto_enumTypes[0]
}

func (x OrderPresence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderPresence.Descriptor instead.
func (OrderPresence) EnumDescriptor() ([]byte, []int) {
	return file_matching_v1_admin_proto_rawDescGZIP(), []int{0}
}

type OrderRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRef) Reset() {
	*x = OrderRef{}
	mi := &file_matching_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRef) ProtoMessage() {}

func (x *OrderRef) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRef.ProtoReflect.Descriptor instead.
func (*OrderRef) Descriptor() ([]byte, []int) {
	return file_matching_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRef) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderRef) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderPresenceRequest) Reset() {
	*x = GetOrderPresenceRequest{}
	mi := &file_matching_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderPresenceRequest) ProtoMessage() {}

func (x *GetOrderPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetOrderPresenceRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderPresenceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderPresenceRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      OrderPresence          `protobuf:"varint,1,opt,name=presence,proto3,enum=matching.v1.OrderPresence" json:"presence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderPresenceResponse) Reset() {
	*x = GetOrderPresenceResponse{}
	mi := &file_matching_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderPresenceResponse) ProtoMessage() {}

func (x *GetOrderPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetOrderPresenceResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderPresenceResponse) GetPresence() OrderPresence {
	if x != nil {
		return x.Presence
	}
	return OrderPresence_ORDER_PRESENCE_UNSPECIFIED
}

type ReconcileOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderRef            `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileOrdersRequest) Reset() {
	*x = ReconcileOrdersRequest{}
	mi := &file_matching_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileOrdersRequest) ProtoMessage() {}

func (x *ReconcileOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileOrdersRequest.ProtoReflect.Descriptor instead.
func (*ReconcileOrdersRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ReconcileOrdersRequest) GetOrders() []*OrderRef {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderPresenceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Presence      OrderPresence          `protobuf:"varint,2,opt,name=presence,proto3,enum=matching.v1.OrderPresence" json:"presence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPresenceResult) Reset() {
	*x = OrderPresenceResult{}
	mi := &file_matching_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPresenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPresenceResult) ProtoMessage() {}

func (x *OrderPresenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPresenceResult.ProtoReflect.Descriptor instead.
func (*OrderPresenceResult) Descriptor() ([]byte, []int) {
	return file_matching_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *OrderPresenceResult) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderPresenceResult) GetPresence() OrderPresence {
	if x != nil {
		return x.Presence
	}
	return OrderPresence_ORDER_PRESENCE_UNSPECIFIED
}

type ReconcileOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*OrderPresenceResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileOrdersResponse) Reset() {
	*x = ReconcileOrdersResponse{}
	mi := &file_matching_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileOrdersResponse) ProtoMessage() {}

func (x *ReconcileOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileOrdersResponse.ProtoReflect.Descriptor instead.
func (*ReconcileOrdersResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ReconcileOrdersResponse) GetResults() []*OrderPresenceResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_matching_v1_admin_proto protoreflect.FileDescriptor

const file_matching_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x17matching/v1/admin.proto\x12\vmatching.v1\"=\n" +
	"\bOrderRef\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"L\n" +
	"\x17GetOrderPresenceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"R\n" +
	"\x18GetOrderPresenceResponse\x126\n" +
	"\bpresence\x18\x01 \x01(\x0e2\x1a.matching.v1.OrderPresenceR\bpresence\"G\n" +
	"\x16ReconcileOrdersRequest\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.matching.v1.OrderRefR\x06orders\"h\n" +
	"\x13OrderPresenceResult\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x126\n" +
	"\bpresence\x18\x02 \x01(\x0e2\x1a.matching.v1.OrderPresenceR\bpresence\"U\n" +
	"\x17ReconcileOrdersResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .matching.v1.OrderPresenceResultR\aresults*\x97\x01\n" +
	"\rOrderPresence\x12\x1e\n" +
	"\x1aORDER_PRESENCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ORDER_PRESENCE_UNKNOWN\x10\x01\x12\x1f\n" +
	"\x1bORDER_PRESENCE_IN_ORDERBOOK\x10\x02\x12)\n" +
	"%ORDER_PRESENCE_KNOWN_NOT_IN_ORDERBOOK\x10\x032\xd5\x01\n" +
	"\x14MatchingAdminService\x12_\n" +
	"\x10GetOrderPresence\x12$.matching.v1.GetOrderPresenceRequest\x1a%.matching.v1.GetOrderPresenceResponse\x12\\\n" +
	"\x0fReconcileOrders\x12#.matching.v1.ReconcileOrdersRequest\x1a$.matching.v1.ReconcileOrdersResponseBJZHgithub.com/Grizzly1127/trading_matchengine/pkg/pb/matching/v1;matchingv1b\x06proto3"

var (
	file_matching_v1_admin_proto_rawDescOnce sync.Once
	file_matching_v1_admin_proto_rawDescData []byte
)

func file_matching_v1_admin_proto_rawDescGZIP() []byte {
	file_matching_v1_admin_proto_rawDescOnce.Do(func() {
		file_matching_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_v1_admin_proto_rawDesc), len(file_matching_v1_admin_proto_rawDesc)))
	})
	return file_matching_v1_admin_proto_rawDescData
}

var file_matching_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_matching_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_matching_v1_admin_proto_goTypes = []any{
	(OrderPresence)(0),               // 0: matching.v1.OrderPresence
	(*OrderRef)(nil),                 // 1: matching.v1.OrderRef
	(*GetOrderPresenceRequest)(nil),  // 2: matching.v1.GetOrderPresenceRequest
	(*GetOrderPresenceResponse)(nil), // 3: matching.v1.GetOrderPresenceResponse
	(*ReconcileOrdersRequest)(nil),   // 4: matching.v1.ReconcileOrdersRequest
	(*OrderPresenceResult)(nil),      // 5: matching.v1.OrderPresenceResult
	(*ReconcileOrdersResponse)(nil),  // 6: matching.v1.ReconcileOrdersResponse
}
var file_matching_v1_admin_proto_depIdxs = []int32{
	0, // 0: matching.v1.GetOrderPresenceResponse.presence:type_name -> matching.v1.OrderPresence
	1, // 1: matching.v1.ReconcileOrdersRequest.orders:type_name -> matching.v1.OrderRef
	0, // 2: matching.v1.OrderPresenceResult.presence:type_name -> matching.v1.OrderPresence
	5, // 3: matching.v1.ReconcileOrdersResponse.results:type_name -> matching.v1.OrderPresenceResult
	2, // 4: matching.v1.MatchingAdminService.GetOrderPresence:input_type -> matching.v1.GetOrderPresenceRequest
	4, // 5: matching.v1.MatchingAdminService.ReconcileOrders:input_type -> matching.v1.ReconcileOrdersRequest
	3, // 6: matching.v1.MatchingAdminService.GetOrderPresence:output_type -> matching.v1.GetOrderPresenceResponse
	6, // 7: matching.v1.MatchingAdminService.ReconcileOrders:output_type -> matching.v1.ReconcileOrdersResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_matching_v1_admin_proto_init() }
func file_matching_v1_admin_proto_init() {
	if File_matching_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_v1_admin_proto_rawDesc), len(file_matching_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matching_v1_admin_proto_goTypes,
		DependencyIndexes: file_matching_v1_admin_proto_depIdxs,
		EnumInfos:         file_matching_v1_admin_proto_enumTypes,
		MessageInfos:      file_matching_v1_admin_proto_msgTypes,
	}.Build()
	File_matching_v1_admin_proto = out.File
	file_matching_v1_admin_proto_goTypes = nil
	file_matching_v1_admin_proto_depIdxs = nil
}
