// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: matching/v1/admin.proto

package matchingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingAdminService_GetOrderPresence_FullMethodName = "/matching.v1.MatchingAdminService/GetOrderPresence"
	MatchingAdminService_ReconcileOrders_FullMethodName  = "/matching.v1.MatchingAdminService/ReconcileOrders"
)

// MatchingAdminServiceClient is the client API for MatchingAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchingAdminService 内网对账接口（无状态查询内存盘口）。
type MatchingAdminServiceClient interface {
	GetOrderPresence(ctx context.Context, in *GetOrderPresenceRequest, opts ...grpc.CallOption) (*GetOrderPresenceResponse, error)
	ReconcileOrders(ctx context.Context, in *ReconcileOrdersRequest, opts ...grpc.CallOption) (*ReconcileOrdersResponse, error)
}

type matchingAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingAdminServiceClient(cc grpc.ClientConnInterface) MatchingAdminServiceClient {
	return &matchingAdminServiceClient{cc}
}

func (c *matchingAdminServiceClient) GetOrderPresence(ctx context.Context, in *GetOrderPresenceRequest, opts ...grpc.CallOption) (*GetOrderPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderPresenceResponse)
	err := c.cc.Invoke(ctx, MatchingAdminService_GetOrderPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingAdminServiceClient) ReconcileOrders(ctx context.Context, in *ReconcileOrdersRequest, opts ...grpc.CallOption) (*ReconcileOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileOrdersResponse)
	err := c.cc.Invoke(ctx, MatchingAdminService_ReconcileOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingAdminServiceServer is the server API for MatchingAdminService service.
// All implementations must embed UnimplementedMatchingAdminServiceServer
// for forward compatibility.
//
// MatchingAdminService 内网对账接口（无状态查询内存盘口）。
type MatchingAdminServiceServer interface {
	GetOrderPresence(context.Context, *GetOrderPresenceRequest) (*GetOrderPresenceResponse, error)
	ReconcileOrders(context.Context, *ReconcileOrdersRequest) (*ReconcileOrdersResponse, error)
	mustEmbedUnimplementedMatchingAdminServiceServer()
}

// UnimplementedMatchingAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingAdminServiceServer struct{}

func (UnimplementedMatchingAdminServiceServer) GetOrderPresence(context.Context, *GetOrderPresenceRequest) (*GetOrderPresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderPresence not implemented")
}
func (UnimplementedMatchingAdminServiceServer) ReconcileOrders(context.Context, *ReconcileOrdersRequest) (*ReconcileOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileOrders not implemented")
}
func (UnimplementedMatchingAdminServiceServer) mustEmbedUnimplementedMatchingAdminServiceServer() {}
func (UnimplementedMatchingAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeMatchingAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingAdminServiceServer will
// result in compilation errors.
type UnsafeMatchingAdminServiceServer interface {
	mustEmbedUnimplementedMatchingAdminServiceServer()
}

func RegisterMatchingAdminServiceServer(s grpc.ServiceRegistrar, srv MatchingAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchingAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingAdminService_ServiceDesc, srv)
}

func _MatchingAdminService_GetOrderPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingAdminServiceServer).GetOrderPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingAdminService_GetOrderPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingAdminServiceServer).GetOrderPresence(ctx, req.(*GetOrderPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingAdminService_ReconcileOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingAdminServiceServer).ReconcileOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingAdminService_ReconcileOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingAdminServiceServer).ReconcileOrders(ctx, req.(*ReconcileOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingAdminService_ServiceDesc is the grpc.ServiceDesc for MatchingAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matching.v1.MatchingAdminService",
	HandlerType: (*MatchingAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderPresence",
			Handler:    _MatchingAdminService_GetOrderPresence_Handler,
		},
		{
			MethodName: "ReconcileOrders",
			Handler:    _MatchingAdminService_ReconcileOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matching/v1/admin.proto",
}
