// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: matching/v1/commands.proto

package matchingv1

import (
	v1 "github.com/Grizzly1127/trading_matchengine/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NewOrderCommand 下单命令（Kafka order.commands / WAL payload）。
type NewOrderCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId uint64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Order     *v1.Order              `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	// 第 3 步 Kafka 对齐：消费位点（第 2 步本地 WAL 可填 0）。
	KafkaPartition uint32 `protobuf:"varint,3,opt,name=kafka_partition,json=kafkaPartition,proto3" json:"kafka_partition,omitempty"`
	KafkaOffset    uint64 `protobuf:"varint,4,opt,name=kafka_offset,json=kafkaOffset,proto3" json:"kafka_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NewOrderCommand) Reset() {
	*x = NewOrderCommand{}
	mi := &file_matching_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOrderCommand) ProtoMessage() {}

func (x *NewOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOrderCommand.ProtoReflect.Descriptor instead.
func (*NewOrderCommand) Descriptor() ([]byte, []int) {
	return file_matching_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *NewOrderCommand) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *NewOrderCommand) GetOrder() *v1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *NewOrderCommand) GetKafkaPartition() uint32 {
	if x != nil {
		return x.KafkaPartition
	}
	return 0
}

func (x *NewOrderCommand) GetKafkaOffset() uint64 {
	if x != nil {
		return x.KafkaOffset
	}
	return 0
}

// CancelOrderCommand 撤单命令；目标订单不存在时幂等忽略。
type CancelOrderCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      uint64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Symbol         string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId        uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	KafkaPartition uint32                 `protobuf:"varint,4,opt,name=kafka_partition,json=kafkaPartition,proto3" json:"kafka_partition,omitempty"`
	KafkaOffset    uint64                 `protobuf:"varint,5,opt,name=kafka_offset,json=kafkaOffset,proto3" json:"kafka_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelOrderCommand) Reset() {
	*x = CancelOrderCommand{}
	mi := &file_matching_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderCommand) ProtoMessage() {}

func (x *CancelOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderCommand.ProtoReflect.Descriptor instead.
func (*CancelOrderCommand) Descriptor() ([]byte, []int) {
	return file_matching_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOrderCommand) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *CancelOrderCommand) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderCommand) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderCommand) GetKafkaPartition() uint32 {
	if x != nil {
		return x.KafkaPartition
	}
	return 0
}

func (x *CancelOrderCommand) GetKafkaOffset() uint64 {
	if x != nil {
		return x.KafkaOffset
	}
	return 0
}

var File_matching_v1_commands_proto protoreflect.FileDescriptor

const file_matching_v1_commands_proto_rawDesc = "" +
	"\n" +
	"\x1amatching/v1/commands.proto\x12\vmatching.v1\x1a\x15common/v1/types.proto\"\xa4\x01\n" +
	"\x0fNewOrderCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x04R\tcommandId\x12&\n" +
	"\x05order\x18\x02 \x01(\v2\x10.common.v1.OrderR\x05order\x12'\n" +
	"\x0fkafka_partition\x18\x03 \x01(\rR\x0ekafkaPartition\x12!\n" +
	"\fkafka_offset\x18\x04 \x01(\x04R\vkafkaOffset\"\xb2\x01\n" +
	"\x12CancelOrderCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x04R\tcommandId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12'\n" +
	"\x0fkafka_partition\x18\x04 \x01(\rR\x0ekafkaPartition\x12!\n" +
	"\fkafka_offset\x18\x05 \x01(\x04R\vkafkaOffsetBJZHgithub.com/Grizzly1127/trading_matchengine/pkg/pb/matching/v1;matchingv1b\x06proto3"

var (
	file_matching_v1_commands_proto_rawDescOnce sync.Once
	file_matching_v1_commands_proto_rawDescData []byte
)

func file_matching_v1_commands_proto_rawDescGZIP() []byte {
	file_matching_v1_commands_proto_rawDescOnce.Do(func() {
		file_matching_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_v1_commands_proto_rawDesc), len(file_matching_v1_commands_proto_rawDesc)))
	})
	return file_matching_v1_commands_proto_rawDescData
}

var file_matching_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_matching_v1_commands_proto_goTypes = []any{
	(*NewOrderCommand)(nil),    // 0: matching.v1.NewOrderCommand
	(*CancelOrderCommand)(nil), // 1: matching.v1.CancelOrderCommand
	(*v1.Order)(nil),           // 2: common.v1.Order
}
var file_matching_v1_commands_proto_depIdxs = []int32{
	2, // 0: matching.v1.NewOrderCommand.order:type_name -> common.v1.Order
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_matching_v1_commands_proto_init() }
func file_matching_v1_commands_proto_init() {
	if File_matching_v1_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_v1_commands_proto_rawDesc), len(file_matching_v1_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matching_v1_commands_proto_goTypes,
		DependencyIndexes: file_matching_v1_commands_proto_depIdxs,
		MessageInfos:      file_matching_v1_commands_proto_msgTypes,
	}.Build()
	File_matching_v1_commands_proto = out.File
	file_matching_v1_commands_proto_goTypes = nil
	file_matching_v1_commands_proto_depIdxs = nil
}
