// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: matching/v1/envelope.proto

package matchingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderCommandEnvelope order.commands topic 单条消息体。
type OrderCommandEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*OrderCommandEnvelope_NewOrder
	//	*OrderCommandEnvelope_CancelOrder
	Command       isOrderCommandEnvelope_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCommandEnvelope) Reset() {
	*x = OrderCommandEnvelope{}
	mi := &file_matching_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCommandEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommandEnvelope) ProtoMessage() {}

func (x *OrderCommandEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommandEnvelope.ProtoReflect.Descriptor instead.
func (*OrderCommandEnvelope) Descriptor() ([]byte, []int) {
	return file_matching_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCommandEnvelope) GetCommand() isOrderCommandEnvelope_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *OrderCommandEnvelope) GetNewOrder() *NewOrderCommand {
	if x != nil {
		if x, ok := x.Command.(*OrderCommandEnvelope_NewOrder); ok {
			return x.NewOrder
		}
	}
	return nil
}

func (x *OrderCommandEnvelope) GetCancelOrder() *CancelOrderCommand {
	if x != nil {
		if x, ok := x.Command.(*OrderCommandEnvelope_CancelOrder); ok {
			return x.CancelOrder
		}
	}
	return nil
}

type isOrderCommandEnvelope_Command interface {
	isOrderCommandEnvelope_Command()
}

type OrderCommandEnvelope_NewOrder struct {
	NewOrder *NewOrderCommand `protobuf:"bytes,1,opt,name=new_order,json=newOrder,proto3,oneof"`
}

type OrderCommandEnvelope_CancelOrder struct {
	CancelOrder *CancelOrderCommand `protobuf:"bytes,2,opt,name=cancel_order,json=cancelOrder,proto3,oneof"`
}

func (*OrderCommandEnvelope_NewOrder) isOrderCommandEnvelope_Command() {}

func (*OrderCommandEnvelope_CancelOrder) isOrderCommandEnvelope_Command() {}

var File_matching_v1_envelope_proto protoreflect.FileDescriptor

const file_matching_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1amatching/v1/envelope.proto\x12\vmatching.v1\x1a\x1amatching/v1/commands.proto\"\xa4\x01\n" +
	"\x14OrderCommandEnvelope\x12;\n" +
	"\tnew_order\x18\x01 \x01(\v2\x1c.matching.v1.NewOrderCommandH\x00R\bnewOrder\x12D\n" +
	"\fcancel_order\x18\x02 \x01(\v2\x1f.matching.v1.CancelOrderCommandH\x00R\vcancelOrderB\t\n" +
	"\acommandBJZHgithub.com/Grizzly1127/trading_matchengine/pkg/pb/matching/v1;matchingv1b\x06proto3"

var (
	file_matching_v1_envelope_proto_rawDescOnce sync.Once
	file_matching_v1_envelope_proto_rawDescData []byte
)

func file_matching_v1_envelope_proto_rawDescGZIP() []byte {
	file_matching_v1_envelope_proto_rawDescOnce.Do(func() {
		file_matching_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_v1_envelope_proto_rawDesc), len(file_matching_v1_envelope_proto_rawDesc)))
	})
	return file_matching_v1_envelope_proto_rawDescData
}

var file_matching_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_matching_v1_envelope_proto_goTypes = []any{
	(*OrderCommandEnvelope)(nil), // 0: matching.v1.OrderCommandEnvelope
	(*NewOrderCommand)(nil),      // 1: matching.v1.NewOrderCommand
	(*CancelOrderCommand)(nil),   // 2: matching.v1.CancelOrderCommand
}
var file_matching_v1_envelope_proto_depIdxs = []int32{
	1, // 0: matching.v1.OrderCommandEnvelope.new_order:type_name -> matching.v1.NewOrderCommand
	2, // 1: matching.v1.OrderCommandEnvelope.cancel_order:type_name -> matching.v1.CancelOrderCommand
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_matching_v1_envelope_proto_init() }
func file_matching_v1_envelope_proto_init() {
	if File_matching_v1_envelope_proto != nil {
		return
	}
	file_matching_v1_commands_proto_init()
	file_matching_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*OrderCommandEnvelope_NewOrder)(nil),
		(*OrderCommandEnvelope_CancelOrder)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_v1_envelope_proto_rawDesc), len(file_matching_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matching_v1_envelope_proto_goTypes,
		DependencyIndexes: file_matching_v1_envelope_proto_depIdxs,
		MessageInfos:      file_matching_v1_envelope_proto_msgTypes,
	}.Build()
	File_matching_v1_envelope_proto = out.File
	file_matching_v1_envelope_proto_goTypes = nil
	file_matching_v1_envelope_proto_depIdxs = nil
}
