// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: matching/v1/events.proto

package matchingv1

import (
	v1 "github.com/Grizzly1127/trading_matchengine/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchEventType int32

const (
	MatchEventType_MATCH_EVENT_TYPE_UNSPECIFIED MatchEventType = 0
	MatchEventType_ORDER_ACCEPTED               MatchEventType = 1
	MatchEventType_ORDER_FILLED                 MatchEventType = 2
	MatchEventType_ORDER_PARTIAL_FILLED         MatchEventType = 3
	MatchEventType_ORDER_CANCELED               MatchEventType = 4
)

// Enum value maps for MatchEventType.
var (
	MatchEventType_name = map[int32]string{
		0: "MATCH_EVENT_TYPE_UNSPECIFIED",
		1: "ORDER_ACCEPTED",
		2: "ORDER_FILLED",
		3: "ORDER_PARTIAL_FILLED",
		4: "ORDER_CANCELED",
	}
	MatchEventType_value = map[string]int32{
		"MATCH_EVENT_TYPE_UNSPECIFIED": 0,
		"ORDER_ACCEPTED":               1,
		"ORDER_FILLED":                 2,
		"ORDER_PARTIAL_FILLED":         3,
		"ORDER_CANCELED":               4,
	}
)

func (x MatchEventType) Enum() *MatchEventType {
	p := new(MatchEventType)
	*p = x
	return p
}

func (x MatchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_matching_v1_events_proto_enumTypes[0].Descriptor()
}

func (MatchEventType) Type() protoreflect.EnumType {
	return &file_matching_v1_events_proto_enumTypes[0]
}

func (x MatchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchEventType.Descriptor instead.
func (MatchEventType) EnumDescriptor() ([]byte, []int) {
	return file_matching_v1_events_proto_rawDescGZIP(), []int{0}
}

// MatchEvent 订单状态变更（match.events topic）。
type MatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	EventType     MatchEventType         `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=matching.v1.MatchEventType" json:"event_type,omitempty"`
	Order         *v1.Order              `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	WalSeq        uint64                 `protobuf:"varint,6,opt,name=wal_seq,json=walSeq,proto3" json:"wal_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEvent) Reset() {
	*x = MatchEvent{}
	mi := &file_matching_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEvent) ProtoMessage() {}

func (x *MatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEvent.ProtoReflect.Descriptor instead.
func (*MatchEvent) Descriptor() ([]byte, []int) {
	return file_matching_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *MatchEvent) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *MatchEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MatchEvent) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *MatchEvent) GetEventType() MatchEventType {
	if x != nil {
		return x.EventType
	}
	return MatchEventType_MATCH_EVENT_TYPE_UNSPECIFIED
}

func (x *MatchEvent) GetOrder() *v1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *MatchEvent) GetWalSeq() uint64 {
	if x != nil {
		return x.WalSeq
	}
	return 0
}

// TradeEvent 成交记录（trade.events topic）。
type TradeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trade         *v1.Trade              `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	WalSeq        uint64                 `protobuf:"varint,2,opt,name=wal_seq,json=walSeq,proto3" json:"wal_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeEvent) Reset() {
	*x = TradeEvent{}
	mi := &file_matching_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeEvent) ProtoMessage() {}

func (x *TradeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeEvent.ProtoReflect.Descriptor instead.
func (*TradeEvent) Descriptor() ([]byte, []int) {
	return file_matching_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *TradeEvent) GetTrade() *v1.Trade {
	if x != nil {
		return x.Trade
	}
	return nil
}

func (x *TradeEvent) GetWalSeq() uint64 {
	if x != nil {
		return x.WalSeq
	}
	return 0
}

var File_matching_v1_events_proto protoreflect.FileDescriptor

const file_matching_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x18matching/v1/events.proto\x12\vmatching.v1\x1a\x15common/v1/types.proto\"\xdb\x01\n" +
	"\n" +
	"MatchEvent\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x04R\tcommandId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12:\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2\x1b.matching.v1.MatchEventTypeR\teventType\x12&\n" +
	"\x05order\x18\x05 \x01(\v2\x10.common.v1.OrderR\x05order\x12\x17\n" +
	"\awal_seq\x18\x06 \x01(\x04R\x06walSeq\"M\n" +
	"\n" +
	"TradeEvent\x12&\n" +
	"\x05trade\x18\x01 \x01(\v2\x10.common.v1.TradeR\x05trade\x12\x17\n" +
	"\awal_seq\x18\x02 \x01(\x04R\x06walSeq*\x86\x01\n" +
	"\x0eMatchEventType\x12 \n" +
	"\x1cMATCH_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_ACCEPTED\x10\x01\x12\x10\n" +
	"\fORDER_FILLED\x10\x02\x12\x18\n" +
	"\x14ORDER_PARTIAL_FILLED\x10\x03\x12\x12\n" +
	"\x0eORDER_CANCELED\x10\x04BJZHgithub.com/Grizzly1127/trading_matchengine/pkg/pb/matching/v1;matchingv1b\x06proto3"

var (
	file_matching_v1_events_proto_rawDescOnce sync.Once
	file_matching_v1_events_proto_rawDescData []byte
)

func file_matching_v1_events_proto_rawDescGZIP() []byte {
	file_matching_v1_events_proto_rawDescOnce.Do(func() {
		file_matching_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_v1_events_proto_rawDesc), len(file_matching_v1_events_proto_rawDesc)))
	})
	return file_matching_v1_events_proto_rawDescData
}

var file_matching_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_matching_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_matching_v1_events_proto_goTypes = []any{
	(MatchEventType)(0), // 0: matching.v1.MatchEventType
	(*MatchEvent)(nil),  // 1: matching.v1.MatchEvent
	(*TradeEvent)(nil),  // 2: matching.v1.TradeEvent
	(*v1.Order)(nil),    // 3: common.v1.Order
	(*v1.Trade)(nil),    // 4: common.v1.Trade
}
var file_matching_v1_events_proto_depIdxs = []int32{
	0, // 0: matching.v1.MatchEvent.event_type:type_name -> matching.v1.MatchEventType
	3, // 1: matching.v1.MatchEvent.order:type_name -> common.v1.Order
	4, // 2: matching.v1.TradeEvent.trade:type_name -> common.v1.Trade
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_matching_v1_events_proto_init() }
func file_matching_v1_events_proto_init() {
	if File_matching_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_v1_events_proto_rawDesc), len(file_matching_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matching_v1_events_proto_goTypes,
		DependencyIndexes: file_matching_v1_events_proto_depIdxs,
		EnumInfos:         file_matching_v1_events_proto_enumTypes,
		MessageInfos:      file_matching_v1_events_proto_msgTypes,
	}.Build()
	File_matching_v1_events_proto = out.File
	file_matching_v1_events_proto_goTypes = nil
	file_matching_v1_events_proto_depIdxs = nil
}
