// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: matching/v1/snapshot.proto

package matchingv1

import (
	v1 "github.com/Grizzly1127/trading_matchengine/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PriceLevel 同一价格档位的 FIFO 挂单队列。
type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *v1.Decimal            `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Orders        []*v1.Order            `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_matching_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_matching_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *PriceLevel) GetPrice() *v1.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *PriceLevel) GetOrders() []*v1.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Snapshot 单交易对订单簿快照（对齐架构 §5.3）。
type Snapshot struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ShardId string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Symbol  string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 该 symbol 已应用到的 command seq（第 3 步可与 kafka_offset 对齐）。
	SeqId             uint64        `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	TimestampUnixNano int64         `protobuf:"varint,4,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Bids              []*PriceLevel `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks              []*PriceLevel `protobuf:"bytes,6,rep,name=asks,proto3" json:"asks,omitempty"`
	// 活跃订单索引，键为 order_id。
	OrderMap map[uint64]*v1.Order `protobuf:"bytes,7,rep,name=order_map,json=orderMap,proto3" json:"order_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// FNV-64(bids + asks)，加载时校验。
	Checksum      uint64 `protobuf:"varint,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_matching_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_matching_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *Snapshot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Snapshot) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *Snapshot) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *Snapshot) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Snapshot) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *Snapshot) GetOrderMap() map[uint64]*v1.Order {
	if x != nil {
		return x.OrderMap
	}
	return nil
}

func (x *Snapshot) GetChecksum() uint64 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

// ShardManifest shard 级快照位点（data/snapshots/{shard_id}/manifest.pb）。
type ShardManifest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ShardId string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// shard 已恢复到的统一 command seq。
	RecoveredOffset uint64 `protobuf:"varint,2,opt,name=recovered_offset,json=recoveredOffset,proto3" json:"recovered_offset,omitempty"`
	// 各 symbol 最新 snapshot 的 seq_id。
	SymbolSeq         map[string]uint64 `protobuf:"bytes,3,rep,name=symbol_seq,json=symbolSeq,proto3" json:"symbol_seq,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	UpdatedAtUnixNano int64             `protobuf:"varint,4,opt,name=updated_at_unix_nano,json=updatedAtUnixNano,proto3" json:"updated_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShardManifest) Reset() {
	*x = ShardManifest{}
	mi := &file_matching_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardManifest) ProtoMessage() {}

func (x *ShardManifest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardManifest.ProtoReflect.Descriptor instead.
func (*ShardManifest) Descriptor() ([]byte, []int) {
	return file_matching_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *ShardManifest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardManifest) GetRecoveredOffset() uint64 {
	if x != nil {
		return x.RecoveredOffset
	}
	return 0
}

func (x *ShardManifest) GetSymbolSeq() map[string]uint64 {
	if x != nil {
		return x.SymbolSeq
	}
	return nil
}

func (x *ShardManifest) GetUpdatedAtUnixNano() int64 {
	if x != nil {
		return x.UpdatedAtUnixNano
	}
	return 0
}

var File_matching_v1_snapshot_proto protoreflect.FileDescriptor

const file_matching_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1amatching/v1/snapshot.proto\x12\vmatching.v1\x1a\x15common/v1/types.proto\"`\n" +
	"\n" +
	"PriceLevel\x12(\n" +
	"\x05price\x18\x01 \x01(\v2\x12.common.v1.DecimalR\x05price\x12(\n" +
	"\x06orders\x18\x02 \x03(\v2\x10.common.v1.OrderR\x06orders\"\x8b\x03\n" +
	"\bSnapshot\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x15\n" +
	"\x06seq_id\x18\x03 \x01(\x04R\x05seqId\x12.\n" +
	"\x13timestamp_unix_nano\x18\x04 \x01(\x03R\x11timestampUnixNano\x12+\n" +
	"\x04bids\x18\x05 \x03(\v2\x17.matching.v1.PriceLevelR\x04bids\x12+\n" +
	"\x04asks\x18\x06 \x03(\v2\x17.matching.v1.PriceLevelR\x04asks\x12@\n" +
	"\torder_map\x18\a \x03(\v2#.matching.v1.Snapshot.OrderMapEntryR\borderMap\x12\x1a\n" +
	"\bchecksum\x18\b \x01(\x04R\bchecksum\x1aM\n" +
	"\rOrderMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.common.v1.OrderR\x05value:\x028\x01\"\x8e\x02\n" +
	"\rShardManifest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12)\n" +
	"\x10recovered_offset\x18\x02 \x01(\x04R\x0frecoveredOffset\x12H\n" +
	"\n" +
	"symbol_seq\x18\x03 \x03(\v2).matching.v1.ShardManifest.SymbolSeqEntryR\tsymbolSeq\x12/\n" +
	"\x14updated_at_unix_nano\x18\x04 \x01(\x03R\x11updatedAtUnixNano\x1a<\n" +
	"\x0eSymbolSeqEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01BJZHgithub.com/Grizzly1127/trading_matchengine/pkg/pb/matching/v1;matchingv1b\x06proto3"

var (
	file_matching_v1_snapshot_proto_rawDescOnce sync.Once
	file_matching_v1_snapshot_proto_rawDescData []byte
)

func file_matching_v1_snapshot_proto_rawDescGZIP() []byte {
	file_matching_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_matching_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_v1_snapshot_proto_rawDesc), len(file_matching_v1_snapshot_proto_rawDesc)))
	})
	return file_matching_v1_snapshot_proto_rawDescData
}

var file_matching_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_matching_v1_snapshot_proto_goTypes = []any{
	(*PriceLevel)(nil),    // 0: matching.v1.PriceLevel
	(*Snapshot)(nil),      // 1: matching.v1.Snapshot
	(*ShardManifest)(nil), // 2: matching.v1.ShardManifest
	nil,                   // 3: matching.v1.Snapshot.OrderMapEntry
	nil,                   // 4: matching.v1.ShardManifest.SymbolSeqEntry
	(*v1.Decimal)(nil),    // 5: common.v1.Decimal
	(*v1.Order)(nil),      // 6: common.v1.Order
}
var file_matching_v1_snapshot_proto_depIdxs = []int32{
	5, // 0: matching.v1.PriceLevel.price:type_name -> common.v1.Decimal
	6, // 1: matching.v1.PriceLevel.orders:type_name -> common.v1.Order
	0, // 2: matching.v1.Snapshot.bids:type_name -> matching.v1.PriceLevel
	0, // 3: matching.v1.Snapshot.asks:type_name -> matching.v1.PriceLevel
	3, // 4: matching.v1.Snapshot.order_map:type_name -> matching.v1.Snapshot.OrderMapEntry
	4, // 5: matching.v1.ShardManifest.symbol_seq:type_name -> matching.v1.ShardManifest.SymbolSeqEntry
	6, // 6: matching.v1.Snapshot.OrderMapEntry.value:type_name -> common.v1.Order
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_matching_v1_snapshot_proto_init() }
func file_matching_v1_snapshot_proto_init() {
	if File_matching_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_v1_snapshot_proto_rawDesc), len(file_matching_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matching_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_matching_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_matching_v1_snapshot_proto_msgTypes,
	}.Build()
	File_matching_v1_snapshot_proto = out.File
	file_matching_v1_snapshot_proto_goTypes = nil
	file_matching_v1_snapshot_proto_depIdxs = nil
}
