// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: kline/v1/kline.proto

package klinev1

import (
	v1 "github.com/Grizzly1127/trading_matchengine/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKlinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKlinesRequest) Reset() {
	*x = GetKlinesRequest{}
	mi := &file_kline_v1_kline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlinesRequest) ProtoMessage() {}

func (x *GetKlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kline_v1_kline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlinesRequest.ProtoReflect.Descriptor instead.
func (*GetKlinesRequest) Descriptor() ([]byte, []int) {
	return file_kline_v1_kline_proto_rawDescGZIP(), []int{0}
}

func (x *GetKlinesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetKlinesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *GetKlinesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetKlinesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetKlinesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetKlinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Klines        []*Kline               `protobuf:"bytes,1,rep,name=klines,proto3" json:"klines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKlinesResponse) Reset() {
	*x = GetKlinesResponse{}
	mi := &file_kline_v1_kline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlinesResponse) ProtoMessage() {}

func (x *GetKlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kline_v1_kline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlinesResponse.ProtoReflect.Descriptor instead.
func (*GetKlinesResponse) Descriptor() ([]byte, []int) {
	return file_kline_v1_kline_proto_rawDescGZIP(), []int{1}
}

func (x *GetKlinesResponse) GetKlines() []*Kline {
	if x != nil {
		return x.Klines
	}
	return nil
}

type Kline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenTime      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	Open          *v1.Decimal            `protobuf:"bytes,3,opt,name=open,proto3" json:"open,omitempty"`
	High          *v1.Decimal            `protobuf:"bytes,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           *v1.Decimal            `protobuf:"bytes,5,opt,name=low,proto3" json:"low,omitempty"`
	Close         *v1.Decimal            `protobuf:"bytes,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume        *v1.Decimal            `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	IsClosed      bool                   `protobuf:"varint,8,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kline) Reset() {
	*x = Kline{}
	mi := &file_kline_v1_kline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kline) ProtoMessage() {}

func (x *Kline) ProtoReflect() protoreflect.Message {
	mi := &file_kline_v1_kline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kline.ProtoReflect.Descriptor instead.
func (*Kline) Descriptor() ([]byte, []int) {
	return file_kline_v1_kline_proto_rawDescGZIP(), []int{2}
}

func (x *Kline) GetOpenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

func (x *Kline) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

func (x *Kline) GetOpen() *v1.Decimal {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *Kline) GetHigh() *v1.Decimal {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *Kline) GetLow() *v1.Decimal {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *Kline) GetClose() *v1.Decimal {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *Kline) GetVolume() *v1.Decimal {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *Kline) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

// KlineClosedEvent 发布至 Kafka topic kline.raw（bar 闭合通知）。
type KlineClosedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	OpenTimeMs    int64                  `protobuf:"varint,3,opt,name=open_time_ms,json=openTimeMs,proto3" json:"open_time_ms,omitempty"`
	CloseTimeMs   int64                  `protobuf:"varint,4,opt,name=close_time_ms,json=closeTimeMs,proto3" json:"close_time_ms,omitempty"`
	Open          *v1.Decimal            `protobuf:"bytes,5,opt,name=open,proto3" json:"open,omitempty"`
	High          *v1.Decimal            `protobuf:"bytes,6,opt,name=high,proto3" json:"high,omitempty"`
	Low           *v1.Decimal            `protobuf:"bytes,7,opt,name=low,proto3" json:"low,omitempty"`
	Close         *v1.Decimal            `protobuf:"bytes,8,opt,name=close,proto3" json:"close,omitempty"`
	Volume        *v1.Decimal            `protobuf:"bytes,9,opt,name=volume,proto3" json:"volume,omitempty"`
	TsMs          int64                  `protobuf:"varint,10,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KlineClosedEvent) Reset() {
	*x = KlineClosedEvent{}
	mi := &file_kline_v1_kline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KlineClosedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KlineClosedEvent) ProtoMessage() {}

func (x *KlineClosedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kline_v1_kline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KlineClosedEvent.ProtoReflect.Descriptor instead.
func (*KlineClosedEvent) Descriptor() ([]byte, []int) {
	return file_kline_v1_kline_proto_rawDescGZIP(), []int{3}
}

func (x *KlineClosedEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *KlineClosedEvent) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *KlineClosedEvent) GetOpenTimeMs() int64 {
	if x != nil {
		return x.OpenTimeMs
	}
	return 0
}

func (x *KlineClosedEvent) GetCloseTimeMs() int64 {
	if x != nil {
		return x.CloseTimeMs
	}
	return 0
}

func (x *KlineClosedEvent) GetOpen() *v1.Decimal {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *KlineClosedEvent) GetHigh() *v1.Decimal {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *KlineClosedEvent) GetLow() *v1.Decimal {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *KlineClosedEvent) GetClose() *v1.Decimal {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *KlineClosedEvent) GetVolume() *v1.Decimal {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *KlineClosedEvent) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

var File_kline_v1_kline_proto protoreflect.FileDescriptor

const file_kline_v1_kline_proto_rawDesc = "" +
	"\n" +
	"\x14kline/v1/kline.proto\x12\bkline.v1\x1a\x15common/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\x10GetKlinesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"<\n" +
	"\x11GetKlinesResponse\x12'\n" +
	"\x06klines\x18\x01 \x03(\v2\x0f.kline.v1.KlineR\x06klines\"\xe4\x02\n" +
	"\x05Kline\x127\n" +
	"\topen_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bopenTime\x129\n" +
	"\n" +
	"close_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcloseTime\x12&\n" +
	"\x04open\x18\x03 \x01(\v2\x12.common.v1.DecimalR\x04open\x12&\n" +
	"\x04high\x18\x04 \x01(\v2\x12.common.v1.DecimalR\x04high\x12$\n" +
	"\x03low\x18\x05 \x01(\v2\x12.common.v1.DecimalR\x03low\x12(\n" +
	"\x05close\x18\x06 \x01(\v2\x12.common.v1.DecimalR\x05close\x12*\n" +
	"\x06volume\x18\a \x01(\v2\x12.common.v1.DecimalR\x06volume\x12\x1b\n" +
	"\tis_closed\x18\b \x01(\bR\bisClosed\"\xed\x02\n" +
	"\x10KlineClosedEvent\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12 \n" +
	"\fopen_time_ms\x18\x03 \x01(\x03R\n" +
	"openTimeMs\x12\"\n" +
	"\rclose_time_ms\x18\x04 \x01(\x03R\vcloseTimeMs\x12&\n" +
	"\x04open\x18\x05 \x01(\v2\x12.common.v1.DecimalR\x04open\x12&\n" +
	"\x04high\x18\x06 \x01(\v2\x12.common.v1.DecimalR\x04high\x12$\n" +
	"\x03low\x18\a \x01(\v2\x12.common.v1.DecimalR\x03low\x12(\n" +
	"\x05close\x18\b \x01(\v2\x12.common.v1.DecimalR\x05close\x12*\n" +
	"\x06volume\x18\t \x01(\v2\x12.common.v1.DecimalR\x06volume\x12\x13\n" +
	"\x05ts_ms\x18\n" +
	" \x01(\x03R\x04tsMs2T\n" +
	"\fKlineService\x12D\n" +
	"\tGetKlines\x12\x1a.kline.v1.GetKlinesRequest\x1a\x1b.kline.v1.GetKlinesResponseBDZBgithub.com/Grizzly1127/trading_matchengine/pkg/pb/kline/v1;klinev1b\x06proto3"

var (
	file_kline_v1_kline_proto_rawDescOnce sync.Once
	file_kline_v1_kline_proto_rawDescData []byte
)

func file_kline_v1_kline_proto_rawDescGZIP() []byte {
	file_kline_v1_kline_proto_rawDescOnce.Do(func() {
		file_kline_v1_kline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kline_v1_kline_proto_rawDesc), len(file_kline_v1_kline_proto_rawDesc)))
	})
	return file_kline_v1_kline_proto_rawDescData
}

var file_kline_v1_kline_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kline_v1_kline_proto_goTypes = []any{
	(*GetKlinesRequest)(nil),      // 0: kline.v1.GetKlinesRequest
	(*GetKlinesResponse)(nil),     // 1: kline.v1.GetKlinesResponse
	(*Kline)(nil),                 // 2: kline.v1.Kline
	(*KlineClosedEvent)(nil),      // 3: kline.v1.KlineClosedEvent
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*v1.Decimal)(nil),            // 5: common.v1.Decimal
}
var file_kline_v1_kline_proto_depIdxs = []int32{
	4,  // 0: kline.v1.GetKlinesRequest.start_time:type_name -> google.protobuf.Timestamp
	4,  // 1: kline.v1.GetKlinesRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 2: kline.v1.GetKlinesResponse.klines:type_name -> kline.v1.Kline
	4,  // 3: kline.v1.Kline.open_time:type_name -> google.protobuf.Timestamp
	4,  // 4: kline.v1.Kline.close_time:type_name -> google.protobuf.Timestamp
	5,  // 5: kline.v1.Kline.open:type_name -> common.v1.Decimal
	5,  // 6: kline.v1.Kline.high:type_name -> common.v1.Decimal
	5,  // 7: kline.v1.Kline.low:type_name -> common.v1.Decimal
	5,  // 8: kline.v1.Kline.close:type_name -> common.v1.Decimal
	5,  // 9: kline.v1.Kline.volume:type_name -> common.v1.Decimal
	5,  // 10: kline.v1.KlineClosedEvent.open:type_name -> common.v1.Decimal
	5,  // 11: kline.v1.KlineClosedEvent.high:type_name -> common.v1.Decimal
	5,  // 12: kline.v1.KlineClosedEvent.low:type_name -> common.v1.Decimal
	5,  // 13: kline.v1.KlineClosedEvent.close:type_name -> common.v1.Decimal
	5,  // 14: kline.v1.KlineClosedEvent.volume:type_name -> common.v1.Decimal
	0,  // 15: kline.v1.KlineService.GetKlines:input_type -> kline.v1.GetKlinesRequest
	1,  // 16: kline.v1.KlineService.GetKlines:output_type -> kline.v1.GetKlinesResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_kline_v1_kline_proto_init() }
func file_kline_v1_kline_proto_init() {
	if File_kline_v1_kline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kline_v1_kline_proto_rawDesc), len(file_kline_v1_kline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kline_v1_kline_proto_goTypes,
		DependencyIndexes: file_kline_v1_kline_proto_depIdxs,
		MessageInfos:      file_kline_v1_kline_proto_msgTypes,
	}.Build()
	File_kline_v1_kline_proto = out.File
	file_kline_v1_kline_proto_goTypes = nil
	file_kline_v1_kline_proto_depIdxs = nil
}
