// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: order/v1/admin.proto

package orderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderAdminService_ListReconcileOrders_FullMethodName = "/order.v1.OrderAdminService/ListReconcileOrders"
	OrderAdminService_GetOrderStatuses_FullMethodName    = "/order.v1.OrderAdminService/GetOrderStatuses"
)

// OrderAdminServiceClient is the client API for OrderAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderAdminService 内网管理接口（撮合启动对账 §5.6）。
type OrderAdminServiceClient interface {
	// ListReconcileOrders 返回指定交易对 PENDING/PARTIAL 订单（供 Orderbook diff）。
	ListReconcileOrders(ctx context.Context, in *ListReconcileOrdersRequest, opts ...grpc.CallOption) (*ListReconcileOrdersResponse, error)
	// GetOrderStatuses 批量查询订单状态（校验盘口孤儿单）。
	GetOrderStatuses(ctx context.Context, in *GetOrderStatusesRequest, opts ...grpc.CallOption) (*GetOrderStatusesResponse, error)
}

type orderAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderAdminServiceClient(cc grpc.ClientConnInterface) OrderAdminServiceClient {
	return &orderAdminServiceClient{cc}
}

func (c *orderAdminServiceClient) ListReconcileOrders(ctx context.Context, in *ListReconcileOrdersRequest, opts ...grpc.CallOption) (*ListReconcileOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReconcileOrdersResponse)
	err := c.cc.Invoke(ctx, OrderAdminService_ListReconcileOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderAdminServiceClient) GetOrderStatuses(ctx context.Context, in *GetOrderStatusesRequest, opts ...grpc.CallOption) (*GetOrderStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderStatusesResponse)
	err := c.cc.Invoke(ctx, OrderAdminService_GetOrderStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderAdminServiceServer is the server API for OrderAdminService service.
// All implementations must embed UnimplementedOrderAdminServiceServer
// for forward compatibility.
//
// OrderAdminService 内网管理接口（撮合启动对账 §5.6）。
type OrderAdminServiceServer interface {
	// ListReconcileOrders 返回指定交易对 PENDING/PARTIAL 订单（供 Orderbook diff）。
	ListReconcileOrders(context.Context, *ListReconcileOrdersRequest) (*ListReconcileOrdersResponse, error)
	// GetOrderStatuses 批量查询订单状态（校验盘口孤儿单）。
	GetOrderStatuses(context.Context, *GetOrderStatusesRequest) (*GetOrderStatusesResponse, error)
	mustEmbedUnimplementedOrderAdminServiceServer()
}

// UnimplementedOrderAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderAdminServiceServer struct{}

func (UnimplementedOrderAdminServiceServer) ListReconcileOrders(context.Context, *ListReconcileOrdersRequest) (*ListReconcileOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReconcileOrders not implemented")
}
func (UnimplementedOrderAdminServiceServer) GetOrderStatuses(context.Context, *GetOrderStatusesRequest) (*GetOrderStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderStatuses not implemented")
}
func (UnimplementedOrderAdminServiceServer) mustEmbedUnimplementedOrderAdminServiceServer() {}
func (UnimplementedOrderAdminServiceServer) testEmbeddedByValue()                           {}

// UnsafeOrderAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderAdminServiceServer will
// result in compilation errors.
type UnsafeOrderAdminServiceServer interface {
	mustEmbedUnimplementedOrderAdminServiceServer()
}

func RegisterOrderAdminServiceServer(s grpc.ServiceRegistrar, srv OrderAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderAdminService_ServiceDesc, srv)
}

func _OrderAdminService_ListReconcileOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReconcileOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderAdminServiceServer).ListReconcileOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderAdminService_ListReconcileOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderAdminServiceServer).ListReconcileOrders(ctx, req.(*ListReconcileOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderAdminService_GetOrderStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderAdminServiceServer).GetOrderStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderAdminService_GetOrderStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderAdminServiceServer).GetOrderStatuses(ctx, req.(*GetOrderStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderAdminService_ServiceDesc is the grpc.ServiceDesc for OrderAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.OrderAdminService",
	HandlerType: (*OrderAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListReconcileOrders",
			Handler:    _OrderAdminService_ListReconcileOrders_Handler,
		},
		{
			MethodName: "GetOrderStatuses",
			Handler:    _OrderAdminService_GetOrderStatuses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/v1/admin.proto",
}
