// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: order/v1/admin.proto

package orderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReconcileOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconcileOrdersRequest) Reset() {
	*x = ListReconcileOrdersRequest{}
	mi := &file_order_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconcileOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconcileOrdersRequest) ProtoMessage() {}

func (x *ListReconcileOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconcileOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListReconcileOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ListReconcileOrdersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type ReconcileOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileOrder) Reset() {
	*x = ReconcileOrder{}
	mi := &file_order_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileOrder) ProtoMessage() {}

func (x *ReconcileOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileOrder.ProtoReflect.Descriptor instead.
func (*ReconcileOrder) Descriptor() ([]byte, []int) {
	return file_order_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ReconcileOrder) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReconcileOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListReconcileOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*ReconcileOrder      `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconcileOrdersResponse) Reset() {
	*x = ListReconcileOrdersResponse{}
	mi := &file_order_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconcileOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconcileOrdersResponse) ProtoMessage() {}

func (x *ListReconcileOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconcileOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListReconcileOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListReconcileOrdersResponse) GetOrders() []*ReconcileOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrderStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderIds      []uint64               `protobuf:"varint,2,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusesRequest) Reset() {
	*x = GetOrderStatusesRequest{}
	mi := &file_order_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusesRequest) ProtoMessage() {}

func (x *GetOrderStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusesRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusesRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderStatusesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderStatusesRequest) GetOrderIds() []uint64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type OrderStatusRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusRef) Reset() {
	*x = OrderStatusRef{}
	mi := &file_order_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusRef) ProtoMessage() {}

func (x *OrderStatusRef) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusRef.ProtoReflect.Descriptor instead.
func (*OrderStatusRef) Descriptor() ([]byte, []int) {
	return file_order_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *OrderStatusRef) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderStatusRef) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderStatusRef) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetOrderStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderStatusRef      `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusesResponse) Reset() {
	*x = GetOrderStatusesResponse{}
	mi := &file_order_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusesResponse) ProtoMessage() {}

func (x *GetOrderStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusesResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusesResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderStatusesResponse) GetOrders() []*OrderStatusRef {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_order_v1_admin_proto protoreflect.FileDescriptor

const file_order_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/admin.proto\x12\border.v1\"4\n" +
	"\x1aListReconcileOrdersRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"C\n" +
	"\x0eReconcileOrder\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"O\n" +
	"\x1bListReconcileOrdersResponse\x120\n" +
	"\x06orders\x18\x01 \x03(\v2\x18.order.v1.ReconcileOrderR\x06orders\"N\n" +
	"\x17GetOrderStatusesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1b\n" +
	"\torder_ids\x18\x02 \x03(\x04R\borderIds\"Y\n" +
	"\x0eOrderStatusRef\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"L\n" +
	"\x18GetOrderStatusesResponse\x120\n" +
	"\x06orders\x18\x01 \x03(\v2\x18.order.v1.OrderStatusRefR\x06orders2\xd2\x01\n" +
	"\x11OrderAdminService\x12b\n" +
	"\x13ListReconcileOrders\x12$.order.v1.ListReconcileOrdersRequest\x1a%.order.v1.ListReconcileOrdersResponse\x12Y\n" +
	"\x10GetOrderStatuses\x12!.order.v1.GetOrderStatusesRequest\x1a\".order.v1.GetOrderStatusesResponseBDZBgithub.com/Grizzly1127/trading_matchengine/pkg/pb/order/v1;orderv1b\x06proto3"

var (
	file_order_v1_admin_proto_rawDescOnce sync.Once
	file_order_v1_admin_proto_rawDescData []byte
)

func file_order_v1_admin_proto_rawDescGZIP() []byte {
	file_order_v1_admin_proto_rawDescOnce.Do(func() {
		file_order_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_admin_proto_rawDesc), len(file_order_v1_admin_proto_rawDesc)))
	})
	return file_order_v1_admin_proto_rawDescData
}

var file_order_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_order_v1_admin_proto_goTypes = []any{
	(*ListReconcileOrdersRequest)(nil),  // 0: order.v1.ListReconcileOrdersRequest
	(*ReconcileOrder)(nil),              // 1: order.v1.ReconcileOrder
	(*ListReconcileOrdersResponse)(nil), // 2: order.v1.ListReconcileOrdersResponse
	(*GetOrderStatusesRequest)(nil),     // 3: order.v1.GetOrderStatusesRequest
	(*OrderStatusRef)(nil),              // 4: order.v1.OrderStatusRef
	(*GetOrderStatusesResponse)(nil),    // 5: order.v1.GetOrderStatusesResponse
}
var file_order_v1_admin_proto_depIdxs = []int32{
	1, // 0: order.v1.ListReconcileOrdersResponse.orders:type_name -> order.v1.ReconcileOrder
	4, // 1: order.v1.GetOrderStatusesResponse.orders:type_name -> order.v1.OrderStatusRef
	0, // 2: order.v1.OrderAdminService.ListReconcileOrders:input_type -> order.v1.ListReconcileOrdersRequest
	3, // 3: order.v1.OrderAdminService.GetOrderStatuses:input_type -> order.v1.GetOrderStatusesRequest
	2, // 4: order.v1.OrderAdminService.ListReconcileOrders:output_type -> order.v1.ListReconcileOrdersResponse
	5, // 5: order.v1.OrderAdminService.GetOrderStatuses:output_type -> order.v1.GetOrderStatusesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_v1_admin_proto_init() }
func file_order_v1_admin_proto_init() {
	if File_order_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_admin_proto_rawDesc), len(file_order_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_admin_proto_goTypes,
		DependencyIndexes: file_order_v1_admin_proto_depIdxs,
		MessageInfos:      file_order_v1_admin_proto_msgTypes,
	}.Build()
	File_order_v1_admin_proto = out.File
	file_order_v1_admin_proto_goTypes = nil
	file_order_v1_admin_proto_depIdxs = nil
}
