// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: order/v1/balance.proto

package orderv1

import (
	v1 "github.com/Grizzly1127/trading_matchengine/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_order_v1_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_balance_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBalanceRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_order_v1_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_balance_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type ListBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBalancesRequest) Reset() {
	*x = ListBalancesRequest{}
	mi := &file_order_v1_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBalancesRequest) ProtoMessage() {}

func (x *ListBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBalancesRequest.ProtoReflect.Descriptor instead.
func (*ListBalancesRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_balance_proto_rawDescGZIP(), []int{2}
}

func (x *ListBalancesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*Balance             `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBalancesResponse) Reset() {
	*x = ListBalancesResponse{}
	mi := &file_order_v1_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBalancesResponse) ProtoMessage() {}

func (x *ListBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBalancesResponse.ProtoReflect.Descriptor instead.
func (*ListBalancesResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_balance_proto_rawDescGZIP(), []int{3}
}

func (x *ListBalancesResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         string                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Balance       *v1.Decimal            `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Frozen        *v1.Decimal            `protobuf:"bytes,3,opt,name=frozen,proto3" json:"frozen,omitempty"`
	Available     *v1.Decimal            `protobuf:"bytes,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_order_v1_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_order_v1_balance_proto_rawDescGZIP(), []int{4}
}

func (x *Balance) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Balance) GetBalance() *v1.Decimal {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *Balance) GetFrozen() *v1.Decimal {
	if x != nil {
		return x.Frozen
	}
	return nil
}

func (x *Balance) GetAvailable() *v1.Decimal {
	if x != nil {
		return x.Available
	}
	return nil
}

type UpdateBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Business      string                 `protobuf:"bytes,3,opt,name=business,proto3" json:"business,omitempty"`
	BusinessId    uint64                 `protobuf:"varint,4,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Change        *v1.Decimal            `protobuf:"bytes,5,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceRequest) Reset() {
	*x = UpdateBalanceRequest{}
	mi := &file_order_v1_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceRequest) ProtoMessage() {}

func (x *UpdateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_balance_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateBalanceRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *UpdateBalanceRequest) GetBusiness() string {
	if x != nil {
		return x.Business
	}
	return ""
}

func (x *UpdateBalanceRequest) GetBusinessId() uint64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *UpdateBalanceRequest) GetChange() *v1.Decimal {
	if x != nil {
		return x.Change
	}
	return nil
}

type UpdateBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceResponse) Reset() {
	*x = UpdateBalanceResponse{}
	mi := &file_order_v1_balance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceResponse) ProtoMessage() {}

func (x *UpdateBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_balance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateBalanceResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_balance_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

var File_order_v1_balance_proto protoreflect.FileDescriptor

const file_order_v1_balance_proto_rawDesc = "" +
	"\n" +
	"\x16order/v1/balance.proto\x12\border.v1\x1a\x15common/v1/types.proto\"B\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\"A\n" +
	"\x12GetBalanceResponse\x12+\n" +
	"\abalance\x18\x01 \x01(\v2\x11.order.v1.BalanceR\abalance\".\n" +
	"\x13ListBalancesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"E\n" +
	"\x14ListBalancesResponse\x12-\n" +
	"\bbalances\x18\x01 \x03(\v2\x11.order.v1.BalanceR\bbalances\"\xab\x01\n" +
	"\aBalance\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12,\n" +
	"\abalance\x18\x02 \x01(\v2\x12.common.v1.DecimalR\abalance\x12*\n" +
	"\x06frozen\x18\x03 \x01(\v2\x12.common.v1.DecimalR\x06frozen\x120\n" +
	"\tavailable\x18\x04 \x01(\v2\x12.common.v1.DecimalR\tavailable\"\xae\x01\n" +
	"\x14UpdateBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x1a\n" +
	"\bbusiness\x18\x03 \x01(\tR\bbusiness\x12\x1f\n" +
	"\vbusiness_id\x18\x04 \x01(\x04R\n" +
	"businessId\x12*\n" +
	"\x06change\x18\x05 \x01(\v2\x12.common.v1.DecimalR\x06change\"D\n" +
	"\x15UpdateBalanceResponse\x12+\n" +
	"\abalance\x18\x01 \x01(\v2\x11.order.v1.BalanceR\abalance2\xfa\x01\n" +
	"\x0eBalanceService\x12G\n" +
	"\n" +
	"GetBalance\x12\x1b.order.v1.GetBalanceRequest\x1a\x1c.order.v1.GetBalanceResponse\x12M\n" +
	"\fListBalances\x12\x1d.order.v1.ListBalancesRequest\x1a\x1e.order.v1.ListBalancesResponse\x12P\n" +
	"\rUpdateBalance\x12\x1e.order.v1.UpdateBalanceRequest\x1a\x1f.order.v1.UpdateBalanceResponseBDZBgithub.com/Grizzly1127/trading_matchengine/pkg/pb/order/v1;orderv1b\x06proto3"

var (
	file_order_v1_balance_proto_rawDescOnce sync.Once
	file_order_v1_balance_proto_rawDescData []byte
)

func file_order_v1_balance_proto_rawDescGZIP() []byte {
	file_order_v1_balance_proto_rawDescOnce.Do(func() {
		file_order_v1_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_balance_proto_rawDesc), len(file_order_v1_balance_proto_rawDesc)))
	})
	return file_order_v1_balance_proto_rawDescData
}

var file_order_v1_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_v1_balance_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),     // 0: order.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 1: order.v1.GetBalanceResponse
	(*ListBalancesRequest)(nil),   // 2: order.v1.ListBalancesRequest
	(*ListBalancesResponse)(nil),  // 3: order.v1.ListBalancesResponse
	(*Balance)(nil),               // 4: order.v1.Balance
	(*UpdateBalanceRequest)(nil),  // 5: order.v1.UpdateBalanceRequest
	(*UpdateBalanceResponse)(nil), // 6: order.v1.UpdateBalanceResponse
	(*v1.Decimal)(nil),            // 7: common.v1.Decimal
}
var file_order_v1_balance_proto_depIdxs = []int32{
	4,  // 0: order.v1.GetBalanceResponse.balance:type_name -> order.v1.Balance
	4,  // 1: order.v1.ListBalancesResponse.balances:type_name -> order.v1.Balance
	7,  // 2: order.v1.Balance.balance:type_name -> common.v1.Decimal
	7,  // 3: order.v1.Balance.frozen:type_name -> common.v1.Decimal
	7,  // 4: order.v1.Balance.available:type_name -> common.v1.Decimal
	7,  // 5: order.v1.UpdateBalanceRequest.change:type_name -> common.v1.Decimal
	4,  // 6: order.v1.UpdateBalanceResponse.balance:type_name -> order.v1.Balance
	0,  // 7: order.v1.BalanceService.GetBalance:input_type -> order.v1.GetBalanceRequest
	2,  // 8: order.v1.BalanceService.ListBalances:input_type -> order.v1.ListBalancesRequest
	5,  // 9: order.v1.BalanceService.UpdateBalance:input_type -> order.v1.UpdateBalanceRequest
	1,  // 10: order.v1.BalanceService.GetBalance:output_type -> order.v1.GetBalanceResponse
	3,  // 11: order.v1.BalanceService.ListBalances:output_type -> order.v1.ListBalancesResponse
	6,  // 12: order.v1.BalanceService.UpdateBalance:output_type -> order.v1.UpdateBalanceResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_order_v1_balance_proto_init() }
func file_order_v1_balance_proto_init() {
	if File_order_v1_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_balance_proto_rawDesc), len(file_order_v1_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_balance_proto_goTypes,
		DependencyIndexes: file_order_v1_balance_proto_depIdxs,
		MessageInfos:      file_order_v1_balance_proto_msgTypes,
	}.Build()
	File_order_v1_balance_proto = out.File
	file_order_v1_balance_proto_goTypes = nil
	file_order_v1_balance_proto_depIdxs = nil
}
