// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: index/v1/index.proto

package indexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexPriceService_GetIndexPrice_FullMethodName = "/index.v1.IndexPriceService/GetIndexPrice"
)

// IndexPriceServiceClient is the client API for IndexPriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexPriceServiceClient interface {
	GetIndexPrice(ctx context.Context, in *GetIndexPriceRequest, opts ...grpc.CallOption) (*GetIndexPriceResponse, error)
}

type indexPriceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexPriceServiceClient(cc grpc.ClientConnInterface) IndexPriceServiceClient {
	return &indexPriceServiceClient{cc}
}

func (c *indexPriceServiceClient) GetIndexPrice(ctx context.Context, in *GetIndexPriceRequest, opts ...grpc.CallOption) (*GetIndexPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIndexPriceResponse)
	err := c.cc.Invoke(ctx, IndexPriceService_GetIndexPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexPriceServiceServer is the server API for IndexPriceService service.
// All implementations must embed UnimplementedIndexPriceServiceServer
// for forward compatibility.
type IndexPriceServiceServer interface {
	GetIndexPrice(context.Context, *GetIndexPriceRequest) (*GetIndexPriceResponse, error)
	mustEmbedUnimplementedIndexPriceServiceServer()
}

// UnimplementedIndexPriceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexPriceServiceServer struct{}

func (UnimplementedIndexPriceServiceServer) GetIndexPrice(context.Context, *GetIndexPriceRequest) (*GetIndexPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndexPrice not implemented")
}
func (UnimplementedIndexPriceServiceServer) mustEmbedUnimplementedIndexPriceServiceServer() {}
func (UnimplementedIndexPriceServiceServer) testEmbeddedByValue()                           {}

// UnsafeIndexPriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexPriceServiceServer will
// result in compilation errors.
type UnsafeIndexPriceServiceServer interface {
	mustEmbedUnimplementedIndexPriceServiceServer()
}

func RegisterIndexPriceServiceServer(s grpc.ServiceRegistrar, srv IndexPriceServiceServer) {
	// If the following call panics, it indicates UnimplementedIndexPriceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexPriceService_ServiceDesc, srv)
}

func _IndexPriceService_GetIndexPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexPriceServiceServer).GetIndexPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexPriceService_GetIndexPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexPriceServiceServer).GetIndexPrice(ctx, req.(*GetIndexPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexPriceService_ServiceDesc is the grpc.ServiceDesc for IndexPriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexPriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "index.v1.IndexPriceService",
	HandlerType: (*IndexPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndexPrice",
			Handler:    _IndexPriceService_GetIndexPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "index/v1/index.proto",
}
