// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: index/v1/index.proto

package indexv1

import (
	v1 "github.com/Grizzly1127/trading_matchengine/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIndexPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexPriceRequest) Reset() {
	*x = GetIndexPriceRequest{}
	mi := &file_index_v1_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexPriceRequest) ProtoMessage() {}

func (x *GetIndexPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexPriceRequest.ProtoReflect.Descriptor instead.
func (*GetIndexPriceRequest) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{0}
}

func (x *GetIndexPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetIndexPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexPrice    *IndexPrice            `protobuf:"bytes,1,opt,name=index_price,json=indexPrice,proto3" json:"index_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexPriceResponse) Reset() {
	*x = GetIndexPriceResponse{}
	mi := &file_index_v1_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexPriceResponse) ProtoMessage() {}

func (x *GetIndexPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexPriceResponse.ProtoReflect.Descriptor instead.
func (*GetIndexPriceResponse) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{1}
}

func (x *GetIndexPriceResponse) GetIndexPrice() *IndexPrice {
	if x != nil {
		return x.IndexPrice
	}
	return nil
}

type IndexPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         *v1.Decimal            `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Sources       []string               `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources,omitempty"`
	Stale         bool                   `protobuf:"varint,5,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexPrice) Reset() {
	*x = IndexPrice{}
	mi := &file_index_v1_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexPrice) ProtoMessage() {}

func (x *IndexPrice) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexPrice.ProtoReflect.Descriptor instead.
func (*IndexPrice) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{2}
}

func (x *IndexPrice) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IndexPrice) GetPrice() *v1.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *IndexPrice) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *IndexPrice) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *IndexPrice) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

// IndexPriceEvent 发布至 Kafka topic index.price。
type IndexPriceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         *v1.Decimal            `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	TsMs          int64                  `protobuf:"varint,3,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	Sources       []string               `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexPriceEvent) Reset() {
	*x = IndexPriceEvent{}
	mi := &file_index_v1_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexPriceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexPriceEvent) ProtoMessage() {}

func (x *IndexPriceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexPriceEvent.ProtoReflect.Descriptor instead.
func (*IndexPriceEvent) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{3}
}

func (x *IndexPriceEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IndexPriceEvent) GetPrice() *v1.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *IndexPriceEvent) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *IndexPriceEvent) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

var File_index_v1_index_proto protoreflect.FileDescriptor

const file_index_v1_index_proto_rawDesc = "" +
	"\n" +
	"\x14index/v1/index.proto\x12\bindex.v1\x1a\x15common/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x14GetIndexPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"N\n" +
	"\x15GetIndexPriceResponse\x125\n" +
	"\vindex_price\x18\x01 \x01(\v2\x14.index.v1.IndexPriceR\n" +
	"indexPrice\"\xb9\x01\n" +
	"\n" +
	"IndexPrice\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12(\n" +
	"\x05price\x18\x02 \x01(\v2\x12.common.v1.DecimalR\x05price\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\asources\x18\x04 \x03(\tR\asources\x12\x14\n" +
	"\x05stale\x18\x05 \x01(\bR\x05stale\"\x82\x01\n" +
	"\x0fIndexPriceEvent\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12(\n" +
	"\x05price\x18\x02 \x01(\v2\x12.common.v1.DecimalR\x05price\x12\x13\n" +
	"\x05ts_ms\x18\x03 \x01(\x03R\x04tsMs\x12\x18\n" +
	"\asources\x18\x04 \x03(\tR\asources2e\n" +
	"\x11IndexPriceService\x12P\n" +
	"\rGetIndexPrice\x12\x1e.index.v1.GetIndexPriceRequest\x1a\x1f.index.v1.GetIndexPriceResponseBDZBgithub.com/Grizzly1127/trading_matchengine/pkg/pb/index/v1;indexv1b\x06proto3"

var (
	file_index_v1_index_proto_rawDescOnce sync.Once
	file_index_v1_index_proto_rawDescData []byte
)

func file_index_v1_index_proto_rawDescGZIP() []byte {
	file_index_v1_index_proto_rawDescOnce.Do(func() {
		file_index_v1_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_index_v1_index_proto_rawDesc), len(file_index_v1_index_proto_rawDesc)))
	})
	return file_index_v1_index_proto_rawDescData
}

var file_index_v1_index_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_index_v1_index_proto_goTypes = []any{
	(*GetIndexPriceRequest)(nil),  // 0: index.v1.GetIndexPriceRequest
	(*GetIndexPriceResponse)(nil), // 1: index.v1.GetIndexPriceResponse
	(*IndexPrice)(nil),            // 2: index.v1.IndexPrice
	(*IndexPriceEvent)(nil),       // 3: index.v1.IndexPriceEvent
	(*v1.Decimal)(nil),            // 4: common.v1.Decimal
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_index_v1_index_proto_depIdxs = []int32{
	2, // 0: index.v1.GetIndexPriceResponse.index_price:type_name -> index.v1.IndexPrice
	4, // 1: index.v1.IndexPrice.price:type_name -> common.v1.Decimal
	5, // 2: index.v1.IndexPrice.updated_at:type_name -> google.protobuf.Timestamp
	4, // 3: index.v1.IndexPriceEvent.price:type_name -> common.v1.Decimal
	0, // 4: index.v1.IndexPriceService.GetIndexPrice:input_type -> index.v1.GetIndexPriceRequest
	1, // 5: index.v1.IndexPriceService.GetIndexPrice:output_type -> index.v1.GetIndexPriceResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_index_v1_index_proto_init() }
func file_index_v1_index_proto_init() {
	if File_index_v1_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_index_v1_index_proto_rawDesc), len(file_index_v1_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_index_v1_index_proto_goTypes,
		DependencyIndexes: file_index_v1_index_proto_depIdxs,
		MessageInfos:      file_index_v1_index_proto_msgTypes,
	}.Build()
	File_index_v1_index_proto = out.File
	file_index_v1_index_proto_goTypes = nil
	file_index_v1_index_proto_depIdxs = nil
}
